Congrats! You just graduated UVA's BSDS program and got a job working at a movie studio in Hollywood. 

Your boss is the head of the studio and wants to know if they can gain a competitive advantage by predicting new movies that might get high imdb scores (movie rating). 

You would like to be able to explain the model to mere mortals but need a fairly robust and flexible approach so you've chosen to use decision trees to get started. 

In doing so, similar to  great data scientists of the past you remembered the excellent education provided to you at UVA in a undergrad data science course and have outline 20ish steps that will need to be undertaken to complete this task. As always, you will need to make sure to #comment your work heavily. 

 Footnotes: 
-	You can add or combine steps if needed
-	Also, remember to try several methods during evaluation and always be mindful of how the model will be used in practice.
- Make sure all your variables are the correct type (factor, character,numeric, etc.)

In [1]:
import pandas as pd
import numpy as np

In [11]:
#1. Load the data
#Sometimes need to set the working directory back out of a folder that we create a file in

#import os
#os.listdir()
#print(os.getcwd())
#os.chdir('c:\\Users\\Brian Wright\\Documents\\3001Python\\DS-3001')

movie_metadata=pd.read_csv("../data/movie_metadata.csv") # Reading the data

movie_metadata.head() # Printing the first five lines of the dataset

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

2 Ensure all the variables are classified correctly including the target variable and collapse factor variables as needed.

All answers from question 2 are part of the function in question 3.

3 Check for missing variables and correct as needed. Once you've completed the cleaning again create a function that will do this for you in the future. In the submission, include only the function and the function call.

In [ ]:
# Creating a function to clean the dataset

def clean_data(df):
    df = df.dropna()
    df1 = df.drop(columns = ['director_name', 'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name', 'actor_1_facebook_likes', 'gross', 'actor_1_name', 'movie_title', 'actor_3_name', 'plot_keywords', 'movie_imdb_link', 'actor_2_facebook_likes', 'aspect_ratio', 'genres', 'language', 'country', 'content_rating'])
    movies_data = pd.get_dummies(df1, columns = ['color'], drop_first = True)

    return movies_data

movies_data = clean_data(movie_metadata) # Calling the function

movies_data.head() # Ensuring the function worked

,num_critic_for_reviews,duration,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,imdb_score,movie_facebook_likes,color_Color
0,723.0,178.0,886204,4834,0.0,3054.0,237000000.0,2009.0,7.9,33000,True
1,302.0,169.0,471220,48350,0.0,1238.0,300000000.0,2007.0,7.1,0,True
2,602.0,148.0,275868,11700,1.0,994.0,245000000.0,2015.0,6.8,85000,True
3,813.0,164.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,8.5,164000,True
5,462.0,132.0,212204,1873,1.0,738.0,263700000.0,2012.0,6.6,24000,True

4 Guess what, you don't need to scale the data, because DTs don't require this to be done, they make local greedy decisions...keeps getting easier, go to the next step.

5 Determine the baserate or prevalence for the classifier, what does this number mean?

6 Split your data into test, tune, and train. (80/10/10)

7 Create the kfold object for cross validation.

8 Create the scoring metric you will use to evaluate your model and the max depth hyperparameter (grid search)

9 Build the classifier object

10 Use the kfold object and the scoring metric to find the best hyperparameter value for max depth via the grid search method.

11 Fit the model to the training data.

12 What is the best depth value?

13 Print out the model

14 View the results, comment on how the model performed using the metrics you selected.

15 Which variables appear to be contributing the most (variable importance)

16 Use the predict method on the tune data and print out the results.

17 How does the model perform on the tune data?

18 Print out the confusion matrix for the tune data, what does it tell you about the model?

19 What are the top 3 movies based on the tune set? Which variables are most important in predicting the top 3 movies?

20 Use a different hyperparameter for the grid search function and go through the process above again using the tune set.

21 Did the model improve with the new hyperparameter search?

22 Using the better model, predict the test data and print out the results.

23 Summarize what you learned along the way and make recommendations to your boss on how this could be used moving forward, being careful not to over promise.